post https://fsto-phonebook.herokuapp.com/api/persons
Content-Type: application/json

{
    "name": "Jon Snow",
    "number": "55-542-424325"
}

###

post https://fsto-phonebook.herokuapp.com/api/persons
Content-Type: application/json

{
    "name": "Jon Snow",
    "number": "22-412-1214412"
}

###

post https://fsto-phonebook.herokuapp.com/api/persons
Content-Type: application/json

{
    "number": "22-412-1214412"
}

###

post https://fsto-phonebook.herokuapp.com/api/persons
Content-Type: application/json

{
    "name": "Jon Snow"
}